package com.time2key.modularmockserver

import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.RecordedRequest

/**
 * Base class for a dispatcher module that is auto generated by [ServerPathAnnotationProcessor].
 * */
abstract class AutoGeneratedDispatcherModule {

    abstract fun getServerPathAnnotatedFunctions(dispatcherModule: DispatcherModule): ArrayList<ServerPathAnnotatedFunction>

    /**
     * A [ServerPathAnnotatedFunction] that has been auto generated at compile time.
     * */
    protected abstract class AutoGeneratedServerPathAnnotatedFunction(
            override val dispatcherModuleSimpleClassName: String,
            override val simpleFunctionName: String,
            matchingPathRegexString: String,
            override val priorityIfMultiplePathsMatch: Int
    ): ServerPathAnnotatedFunction() {

        override val matchingPathRegex = Regex(matchingPathRegexString)

    }
}