package com.time2key.modularmockserver.internal

/**
 * Base class for auto generated class mapper.
 *
 * One of these will be auto generated by [ServerPathAnnotationProcessor], and it will map all
 * [DispatcherModule]s in the project to the [AutoGeneratedDispatcherModuleInternals].
 * */
abstract class BaseAutoGeneratedClassMapper {
    abstract fun getInternalsForClass(clazz: Class<out Any>): AutoGeneratedDispatcherModuleInternals?
}